##########################################################################################
# Script for aggregating binary graph measures per subject per threshold for LANG 131 ROIs
# For details regarding the 131 ROIs, see Roger et al. (2022). Unraveling the functional attributes of the language connectome

# Written by CG
# 21-11-2022
##########################################################################################
library(tidyverse)
library(janitor)
library(dplyr)
library(tidyr)
library(readr)
library(plyr)
library(readxl)
library(lmerTest)
library(car)
library(Rmisc)
library(tidylog)

rm(list = ls())

# sub-030/SEMVIE-07 was removed ahead of GraphVar analyses because error in conn with "c3wm after erosion/no suprathreshold found"

##########################################################################################
# Import network labeling generated by InLang & by our network overlap calculator --------
Network_overlap_InLang <- read_excel("Network_overlap_InLang.xlsx",
  sheet = "Liberal"
) %>%
  janitor::row_to_names(1)
# Import Community vectors, also contains the gender consensus vectors
Consensus_vector <- read_excel("Consensus_vectors.xlsx") %>%
  mutate_at(vars(starts_with("Consensus")), funs(as.character(as.numeric(.))))

meta_data_0 <- merge(Network_overlap_InLang, Consensus_vector, by = "Region")

# Import meta-data on participants
meta_data_1 <- read_excel("Recap_databases_HC_RS.xlsx") %>%
  dplyr::select(c("Subj_ID", "Project", "Anonymat", "Age", "Gender", "Lat_manuelle", "Education")) %>%
  replace("Subj_ID", seq_len(72)) %>%
  mutate(Gender_c = ifelse(Gender == "M", -0.5, 0.5)) %>%
  mutate_at(vars("Age"), funs(as.numeric(as.character(.))))

# Import data -------------------------------------
# List all txt files & extract the files
listfile <- list.files(getwd(), pattern = "*.txt")
n_subj <- 72
n_threshold <- 8

# Local Metrics-------------------------------------

# Degree centrality-------------------------------
listfile_degree <- listfile[grep("degrees", listfile)]

degree <- ldply(listfile_degree, read.table, header = T, sep = "\t") %>%
  mutate(threshold = rep(c(.05, .07, .1, .12, .15, .17, .2, .25), each = n_subj)) %>%
  relocate(threshold, .after = (X)) %>%
  plyr::rename(c("X" = "Subj_ID")) %>%
  replace("Subj_ID", rep(seq_len(n_subj), times = n_threshold)) %>%
  pivot_longer(
    cols = !c("Subj_ID", "threshold"),
    names_to = "Region",
    values_to = "degree"
  )

# Betweenness centrality-------------------------
listfile_BC <- listfile[grep("betweenness", listfile)]

BC <- ldply(listfile_BC, read.table, header = T, sep = "\t") %>%
  mutate(threshold = rep(c(.05, .07, .1, .12, .15, .17, .2, .25), each = n_subj)) %>%
  relocate(threshold, .after = (X)) %>%
  plyr::rename(c("X" = "Subj_ID")) %>%
  replace("Subj_ID", rep(seq_len(n_subj), times = n_threshold)) %>%
  pivot_longer(
    cols = !c("Subj_ID", "threshold"),
    names_to = "Region",
    values_to = "Betweenness"
  )

# Flow centrality-------------------------------
listfile_flow <- listfile[grep("flow", listfile)]

Flow <- ldply(listfile_flow, read.table, header = T, sep = "\t") %>%
  mutate(threshold = rep(c(.05, .07, .1, .12, .15, .17, .2, .25), each = n_subj)) %>%
  relocate(threshold, .after = (X)) %>%
  plyr::rename(c("X" = "Subj_ID")) %>%
  replace("Subj_ID", rep(seq_len(n_subj), times = n_threshold)) %>%
  pivot_longer(
    cols = !c("Subj_ID", "threshold"),
    names_to = "Region",
    values_to = "Flow_coeff"
  )


# Local efficiency-------------------------------
listfile_Eloc <- listfile[grep("efficiency_local", listfile)]

Eloc <- ldply(listfile_Eloc, read.table, header = T, sep = "\t") %>%
  mutate(threshold = rep(c(.05, .07, .1, .12, .15, .17, .2, .25), each = n_subj)) %>%
  relocate(threshold, .after = (X)) %>%
  plyr::rename(c("X" = "Subj_ID")) %>%
  replace("Subj_ID", rep(seq_len(n_subj), times = n_threshold)) %>%
  pivot_longer(
    cols = !c("Subj_ID", "threshold"),
    names_to = "Region",
    values_to = "Eloc"
  )


# Global Metrics------------------------------------
# Global efficiency & Clustering coefficient global-------------------------
listfile_Glob <- listfile[grep("global", listfile)]

Glob <- ldply(listfile_Glob, read.table, header = T, sep = "\t") %>%
  mutate(threshold = rep(c(.05, .07, .1, .12, .15, .17, .2, .25), each = n_subj)) %>%
  relocate(threshold, .after = (X)) %>%
  plyr::rename(c("X" = "Subj_ID")) %>%
  plyr::rename(c("efficiency_bin" = "Eglob")) %>%
  plyr::rename(c("clusterMean_bu" = "Clustering_coeff_glob")) %>%
  # plyr::rename(c("modularity_louvain_QOut_und" = "Modularity_Q")) %>%
  replace("Subj_ID", rep(seq_len(n_subj), times = n_threshold)) %>%
  dplyr::select(Subj_ID, threshold, Eglob, Clustering_coeff_glob)

# Add the Modularity Q for each threshold from the consensus-based community detection
# See in path/to/GraphVar/RS_Power264_0512/results/Consensus_clustering
Q_consensus <- c(0.5164, 0.5062, 0.4943, 0.5018, 0.5530, 0.5007, 0.4745, 0.4911)
threshold <- c(.05, .07, .1, .12, .15, .17, .2, .25)
output <- cbind(threshold, Q_consensus)

Glob_final <- merge(Glob, output, by.x = "threshold", all = T)



################################################################################
################################################################################
# Merge all data
################################################################################
################################################################################

# For local metrics
tmp_local_0 <- cbind(
  degree,
  Betweenness = BC$Betweenness,
  Flow_coeff = Flow$Flow_coeff,
  Eloc = Eloc$Eloc
)

# Add subject information to local metrics
tmp_local_1 <- merge(meta_data_1, tmp_local_0, by = "Subj_ID") %>%
  relocate(Project, .before = "Subj_ID")

# Add RSNs classification, consensus vectors & global metrics
# DIMENSIONS 72 Subjects * 131 Regions * 8 thresholds

data_full <- merge(tmp_local_1, meta_data_0, by = "Region") %>%
  relocate(Region, .after = threshold) %>%
  relocate(Index.Power264, .before = Region) %>%
  arrange(Subj_ID, Region, threshold) %>%
  merge(., Glob_final %>%
    dplyr::select(Subj_ID, threshold, Eglob, Clustering_coeff_glob, Q_consensus),
  by = c("Subj_ID", "threshold")
  ) %>%
  arrange(Subj_ID, threshold, Region)

# Combining data for each row = one subject
data_local_per_subject <- data_full %>%
  group_by(Subj_ID, threshold) %>%
  summarize_at(vars(degree:Eloc), mean)

data_global_per_subject <- merge(meta_data_1, Glob_final, by = "Subj_ID") %>%
  arrange(Subj_ID, threshold) %>%
  relocate(Project, .before = "Subj_ID")

# DIMENSIONS 72 Subjects * 8 thresholds
data_full_per_subject <- merge(data_global_per_subject, data_local_per_subject, by = c("Subj_ID", "threshold")) %>%
  arrange(Subj_ID, threshold)


# Combining data for each row = one region
data_local_per_region <- data_full %>%
  group_by(Region, threshold) %>%
  summarize_at(vars(degree:Eloc), mean)

data_global_per_region <- merge(data_local_per_region, Glob_final %>%
  group_by(threshold) %>%
  summarize_at(vars(Eglob:Q_consensus), mean), by = "threshold")

# DIMENSIONS 131 Regions * 8 thresholds
data_full_per_region <- merge(data_global_per_region, meta_data_0, by = "Region")
################################################################################
# Output-------------------------------
rm(list = ls()[!ls() %in% c("data_full", "data_full_per_subject", "data_full_per_region")])

